function createfigure(XData1, YData1, YData2, YData3)
%CREATEFIGURE(XData1, YData1, YData2, YData3)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata

%  Auto-generated by MATLAB on 07-Apr-2022 10:07:53

% Create figure
figure1 = figure('Tag','filtervisualizationtool',...
    'Name','Magnitude Response (dB)',...
    'OuterPosition',[1 1 1123.5 489.5]);

% Create axes
axes1 = axes('Tag','fvtool_axes_1','Parent',figure1,...
    'Position',[0.13 0.11 0.755625 0.815]);

% Create line
line(XData1,YData1,'DisplayName','Floating-point (double) SOS',...
    'Tag','magnitude_line',...
    'Parent',axes1,...
    'LineWidth',1);

% Create line
line(XData1,YData2,'DisplayName','Fixed-point (8-bit) SOS',...
    'Tag','magnitude_line',...
    'Parent',axes1,...
    'LineWidth',1,...
    'Color',[0 0.447058823529412 0.741176470588235]);

% Create line
line(XData1,YData3,'DisplayName','Fixed-point (16-bit) SOS',...
    'Tag','magnitude_line',...
    'Parent',axes1,...
    'LineWidth',1,...
    'Color',[1 0 0]);

% Create ylabel
ylabel('Magnitude (dB)','FontSize',12);

% Create xlabel
xlabel('Normalized Frequency (\times\pi rad/sample)','FontSize',12);

% Create title
title('Magnitude Response (dB)','FontSize',12);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.9998779296875]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-113.030479263253 5.07382827727704]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'ContextMenu','Toolbar','XGrid','on','YGrid','on');
% Create axes
axes2 = axes('Tag','fvtool_axes_2','Parent',figure1,...
    'Position',[0.13 0.11 0.755625 0.815]);
axis off

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 0.9998779296875]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'ContextMenu','Toolbar');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',12,'AutoUpdate','off','Location','best');

% uitoolbar currently does not support code generation, enter 'doc uitoolbar' for correct input syntax
% In order to generate code for uitoolbar, you may use GUIDE. Enter 'doc guide' for more information
% uitoolbar(...);

% uipushtool currently does not support code generation, enter 'doc uipushtool' for correct input syntax
% In order to generate code for uipushtool, you may use GUIDE. Enter 'doc guide' for more information
% uipushtool(...);

% uipushtool currently does not support code generation, enter 'doc uipushtool' for correct input syntax
% In order to generate code for uipushtool, you may use GUIDE. Enter 'doc guide' for more information
% uipushtool(...);

% uipushtool currently does not support code generation, enter 'doc uipushtool' for correct input syntax
% In order to generate code for uipushtool, you may use GUIDE. Enter 'doc guide' for more information
% uipushtool(...);

% uipushtool currently does not support code generation, enter 'doc uipushtool' for correct input syntax
% In order to generate code for uipushtool, you may use GUIDE. Enter 'doc guide' for more information
% uipushtool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoolbar currently does not support code generation, enter 'doc uitoolbar' for correct input syntax
% In order to generate code for uitoolbar, you may use GUIDE. Enter 'doc guide' for more information
% uitoolbar(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uitoggletool currently does not support code generation, enter 'doc uitoggletool' for correct input syntax
% In order to generate code for uitoggletool, you may use GUIDE. Enter 'doc guide' for more information
% uitoggletool(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uimenu currently does not support code generation, enter 'doc uimenu' for correct input syntax
% In order to generate code for uimenu, you may use GUIDE. Enter 'doc guide' for more information
% uimenu(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

